server:
  url: http://localhost:${server.port}
  port: 50022
  
spring:
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123
  data:
    mongodb:
      database: mp_authorizations
      host: localhost    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
psp:
  service: MP-PSPSERVICE
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token
  
oauth:
  client_id: mp_authorizations_client
  client_secret: Y2QgZWEgOWMgYzAgNzkgNDQgZGMgYjEgMDUgMTcgNjYgNWEgZDQgOGEgOTEg  
   
amqp:
  transactions:
    queue:
      authorization:
        created:
          request: authorization_created_request_queue

  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events     
          
  authorizations:
    exchange:
      completed:
        authorization: completed_authorization
    queue:
      authorization:
        completed:
          response: authorization_completed_response_queue   

---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_authorizations
      host: localhost
      port: 27018

server:
  url: http://o2c.ovh:${server.port}
