server:
  port: 50066
  
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: mp_breakdowns
      host: localhost
      
#logging:
#  level:
#    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
   
management:
  endpoints:
    web:
      exposure:
        include: "*"    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   
amqp:
  breakdowns:
    exchange:
      created:
        breakdown: created_breakdown
    queue:
      payment:
        completed:
          response: breakdown_payment_created_response_queue        

  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events          
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:50068/validateClient
      
oauth:
  client_id: mp_breakdown_client
  client_secret: ZGMgODQgMTAgMGUgYmQgN2EgNjcgZDUgYzUgN2EgNGUgYzYgMTkgYWEgMDIg

transaction:
  service: MP-TRANSACTIONS
  
beneficiary:
  service: MP-BENEFICIARIES
  
auth:
  service: MP-AUTHSERVER
  path: /oauth/token  

---
spring:
  profiles: integration
  data:
    mongodb:
      database: mp_breakdowns
      host: localhost
      port: 27018
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123      
