server:
  port: 50033
  
spring:
  rabbitmq:
    host: o2c.ovh
    port: 5672
    username: master-pay
    password: master123
  data:
    mongodb:
      database: mp_captures
      host: localhost    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health      
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

authorization:
  service: MP-AUTHORIZATIONS
  
psp:
  service: MP-PSPSERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"    
amqp:
  captures:
    queue:
      transaction:
        status:
          updated:
            request: create_capture_response_queue
    exchange:
      completed:
        capture: completed_capture            
            
  events:
    queue:
      created:
        request: createad_event_queue
    exchange:
      created: created_events
    key:
      created:
        request: events   
